// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// APPClient is the client API for APP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APPClient interface {
	MapReduceResult(ctx context.Context, in *MRResult, opts ...grpc.CallOption) (*MREmpty, error)
}

type aPPClient struct {
	cc grpc.ClientConnInterface
}

func NewAPPClient(cc grpc.ClientConnInterface) APPClient {
	return &aPPClient{cc}
}

func (c *aPPClient) MapReduceResult(ctx context.Context, in *MRResult, opts ...grpc.CallOption) (*MREmpty, error) {
	out := new(MREmpty)
	err := c.cc.Invoke(ctx, "/APP/MapReduceResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APPServer is the server API for APP service.
// All implementations must embed UnimplementedAPPServer
// for forward compatibility
type APPServer interface {
	MapReduceResult(context.Context, *MRResult) (*MREmpty, error)
	mustEmbedUnimplementedAPPServer()
}

// UnimplementedAPPServer must be embedded to have forward compatible implementations.
type UnimplementedAPPServer struct {
}

func (UnimplementedAPPServer) MapReduceResult(context.Context, *MRResult) (*MREmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapReduceResult not implemented")
}
func (UnimplementedAPPServer) mustEmbedUnimplementedAPPServer() {}

// UnsafeAPPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APPServer will
// result in compilation errors.
type UnsafeAPPServer interface {
	mustEmbedUnimplementedAPPServer()
}

func RegisterAPPServer(s grpc.ServiceRegistrar, srv APPServer) {
	s.RegisterService(&APP_ServiceDesc, srv)
}

func _APP_MapReduceResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MRResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APPServer).MapReduceResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/APP/MapReduceResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APPServer).MapReduceResult(ctx, req.(*MRResult))
	}
	return interceptor(ctx, in, info, handler)
}

// APP_ServiceDesc is the grpc.ServiceDesc for APP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "APP",
	HandlerType: (*APPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MapReduceResult",
			Handler:    _APP_MapReduceResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}
